# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Set environment variable
      run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
    - name: Test environment variable
      run: echo ${{ env.RELEASE_VERSION }}
    - name: Check out GitHub repo
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build image and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ github.repository }}:${{ env.RELEASE_VERSION }}
         
